---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
env:
  - PUPPET_GEM_VERSION="3.4.3"
  - PUPPET_GEM_VERSION="3.5.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.6.2" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.7.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.7.1" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="3.7.5" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.7.5" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="3.8.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.8.1" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="3.8.6" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.8.6" STRICT_VARIABLES=yes FUTURE_PARSER=yes

matrix:
  fast_finish: true

notifications:
  email: false
